[book]
authors = ["Nadai2010 y L2 en Espa√±ol"]
language = "es"
multilingual = false
src = "src"
title = "L2 Book"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html.fold]
enable = true
level = 0
